version: "3"

networks:
  backend:
  frontend:

services:
  server:
    image: unfoldingword/dcs:latest
    container_name: dcs-local-gitea

    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - backend
    volumes:
      - .:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: dcs-local-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - backend
    volumes:
      - ./mysql:/var/lib/mysql

  proxy:
    container_name: dcs-local-proxy
    image: nginx
    restart: always
    networks: 
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./scripts:/opt/scripts
    depends_on:
      - server
    entrypoint: /docker-entrypoint.sh /opt/scripts/entrypoint.sh