#!/bin/bash

SCRIPTS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPTS_DIR/functions.sh"

cmd=$1
shift

case $cmd in
  load_sources)
    echo "source $@"
    loadSources "$@"
    ;;
  load_target)
    echo "target $@"
    loadTargets "$@"
    ;;
  add_users)
    echo "add_users $@"
    addUsers "$@"
    ;;
  upload_all_target_repos)
    echo "upload_all_target_repos $@"
    uploadAllTargetRepos "$@"
    ;;
  *)
    cat << EOF
usage: run [load_sources|load_targets|add_users|upload_all_target_repos] <options>

Log a bug at https://github.com/unfoldingWord/dcs-local/issues or email info@door43.org
EOF
    exit 0
    ;;
esac
