#!/bin/bash

SCRIPTS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPTS_DIR/functions.sh"

cmd=$1
shift

case $cmd in
  create_admin_user)
    ensureRootUser
    ;;
  load_sources)
    loadSources "$@"
    ;;
  load_targets)
    loadTargets "$@"
    ;;
  add_users)
    addUsers "$@"
    ;;
  update_targets)
    updateAllTargetRepos
    ;;
  upload_targets)
    uploadAllTargetRepos "$@"
    ;;
  *)
    cat << EOF
usage: run [create_admin_user|load_sources|load_targets|add_users|update_targets|upload_targets] <options>

Log a bug at https://github.com/unfoldingWord/dcs-local/issues or email info@door43.org
EOF
    exit 0
    ;;
esac
